export const Names = [
    "Aglovale",
    "Agravaine",
    "Amr",
    "Andred",
    "Ambrosius",
    "Bagdemagus",
    "Ban",
    "Balan",
    "Balin",
    "Bedivere",
    "Bors",
    "Brangaine",
    "Brangaine",
    "Bruin",
    "Breunor",
    "Brutus",
    "Cador",
    "Caelia",
    "Caradoc",
    "Catigern",
    "Cei",
    "Claudas",
    "Claudin",
    "Culhwch",
    "Cynric",
    "Dagonet",
    "Dinadan",
    "Durnure",
    "Ector",
    "Edern",
    "Elyan",
    "Enide",
    "Erec",
    "Escanor",
    "Evaine",
    "Gaheris",
    "Galahad",
    "Galehault",
    "Galeschin",
    "Gareth",
    "Geraint",
    "Gildas",
    "Girart",
    "Griflet",
    "Gringolet",
    "Guinevak",
    "Guiron",
    "Gwyn",
    "Hengest",
    "Horsa",
    "Isolde",
    "Josephus",
    "Kahedin",
    "Lamorak",
    "Lanval",
    "Laudine",
    "Lionel",
    "Lohengrin",
    "Loholt",
    "Loth",
    "Lucan",
    "Lucius",
    "Lunete",
    "Mabon",
    "Madoc",
    "Maleagant",
    "Meliodas",
    "Modron",
    "Mordred",
    "Morgaine",
    "Morgause",
    "Morholt",
    "Morien",
    "Morvydd",
    "Nimue",
    "Oberon",
    "Orgeluse",
    "Owain",
    "Palamedes",
    "Parcenet",
    "Pellam",
    "Pelleas",
    "Pellinore",
    "Percival",
    "Ragnelle",
    "Rhiannon",
    "Safir",
    "Sagramore",
    "Tor",
    "Urien",
    "Uther",
    "Vortigern",
    "Vortimer",
    "Yvain",
    "Ywain",
    "Zephyranthes",
  ],
  Physiques = [
    "Athletic",
    "Brawny",
    "Corpulent",
    "Delicate",
    "Gaunt",
    "Hulking",
    "Lanky",
    "Ripped",
    "Rugged",
    "Scrawny",
    "Short",
    "Sinewy",
    "Slender",
    "Flabby",
    "Statuesque",
    "Stout",
    "Tiny",
    "Towering",
    "Willowy",
    "Wiry",
  ],
  Faces = [
    "Bloated",
    "Blunt",
    "Bony",
    "Chiseled",
    "Delicate",
    "Elognated",
    "Patrician",
    "Pinched",
    "Hawkish",
    "Broken",
    "Impish",
    "Narrow",
    "Ratlike",
    "Round",
    "Sunken",
    "Sharp",
    "Soft",
    "Square",
    "Wide",
    "Wolfish",
  ],
  Skins = [
    "Battle Scar",
    "Birthmark",
    "Burn Scar",
    "Dark",
    "Makeup",
    "Oily",
    "Pale",
    "Perfect",
    "Pierced",
    "Pockmarked",
    "Reeking",
    "Tattooed",
    "Rosy",
    "Rough",
    "Sallow",
    "Sunburned",
    "Tanned",
    "War Paint",
    "Weathered",
    "Whip Scar",
  ],
  Hairs = [
    "Bald",
    "Braided",
    "Bristly",
    "Cropped",
    "Curly",
    "Disheveled",
    "Dreadlocks",
    "Filthy",
    "Frizzy",
    "Greased",
    "Limp",
    "Long",
    "Luxurious",
    "Mohawk",
    "Oily",
    "Ponytail",
    "Silky",
    "Topknot",
    "Wavy",
    "Wispy",
  ],
  Clothing = [
    "Antique",
    "Bloody",
    "Ceremonial",
    "Decorated",
    "Eccentric",
    "Elegant",
    "Fashionable",
    "Filthy",
    "Flamboyant",
    "Stained",
    "Foreign",
    "Frayed",
    "Frumpy",
    "Livery",
    "Oversized",
    "Patched",
    "Perfumed",
    "Rancid",
    "Torn",
    "Undersized",
  ],
  Virtues = [
    "Ambitious",
    "Cautious",
    "Courageous",
    "Courteous",
    "Curious",
    "Disciplined",
    "Focused",
    "Generous",
    "Gregarious",
    "Honest",
    "Honorable",
    "Humble",
    "Idealistic",
    "Just",
    "Loyal",
    "Merciful",
    "Righteous",
    "Serene",
    "Stoic",
    "Tolerant",
  ],
  Vices = [
    "Aggressive",
    "Arrogant",
    "Bitter",
    "Cowardly",
    "Cruel",
    "Deceitful",
    "Flippant",
    "Gluttonous",
    "Greedy",
    "Irascible",
    "Lazy",
    "Nervous",
    "Prejudiced",
    "Reckless",
    "Rude",
    "Suspicious",
    "Vain",
    "Vengeful",
    "Wasteful",
    "Whiny",
  ],
  Speech = [
    "Blunt",
    "Booming",
    "Breathy",
    "Cryptic",
    "Drawling",
    "Droning",
    "Flowery",
    "Formal",
    "Gravelly",
    "Hoarse",
    "Mumbling",
    "Precise",
    "Quaint",
    "Rambling",
    "Rapid-fire",
    "Dialect",
    "Slow",
    "Squeaky",
    "Stuttering",
    "Whispery",
  ],
  Backgrounds = [
    "Alchemist",
    "Beggar",
    "Butcher",
    "Burglar",
    "Charlatan",
    "Cleric",
    "Cook",
    "Cultist",
    "Gambler",
    "Herbalist",
    "Magician",
    "Mariner",
    "Mercenary",
    "Merchant",
    "Outlaw",
    "Performer",
    "Pickpocket",
    "Smuggler",
    "Student",
    "Tracker",
  ],
  Misfortunes = [
    "Abandoned",
    "Addicted",
    "Blackmailed",
    "Condemned",
    "Cursed",
    "Defrauded",
    "Demoted",
    "Discredited",
    "Disowned",
    "Exiled",
    "Framed",
    "Haunted",
    "Kidnapped",
    "Mutilated",
    "Poor",
    "Pursued",
    "Rejected",
    "Replaced",
    "Robbed",
    "Suspected",
  ],
  Alignments = ["Law", "Neutrality", "Chaos"],
  DungeoneeringGear = [
    "Rope, 50ft",
    "Pulleys",
    "Candles, 5",
    "Chain, 10ft",
    "Chalk, 10",
    "Crowbar",
    "Tinderbox",
    "Grap. hook",
    "Hammer",
    "Waterskin",
    "Lantern",
    "Lamp oil",
    "Padlock",
    "Manacles",
    "Mirror",
    "Pole, 10ft",
    "Sack",
    "Tent",
    "Spikes, 5",
    "Torches, 5",
  ],
  GeneralGear1 = [
    "Air bladder",
    "Bear trap",
    "Shovel",
    "Bellows",
    "Grease",
    "Saw",
    "Bucket",
    "Caltrops",
    "Chisel",
    "Drill",
    "Fishing rod",
    "Marbles",
    "Glue",
    "Pick",
    "Hourglass",
    "Net",
    "Tongs",
    "Lockpicks",
    "Metal file",
    "Nails",
  ],
  GeneralGear2 = [
    "Incense",
    "Sponge",
    "Lens",
    "Perfume",
    "Horn",
    "Bottle",
    "Soap",
    "Spyglass",
    "Tar pot",
    "Twine",
    "Fake jewels",
    "Blank book",
    "Card deck",
    "Dice set",
    "Cook pots",
    "Face paint",
    "Whistle",
    "Instrument",
    "Quill & ink",
    "Small bell",
  ];
